/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5pNzt2YxpOp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function client-channel-comp() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              The Earth is Flat
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Discover the truth about our planet's true shape, as revealed by these esteemed world leaders.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <blockquote className="flex flex-col items-center justify-center space-y-2 rounded-md bg-gray-100 p-4 text-center dark:bg-gray-800">
              <div className="text-lg font-semibold">"The Earth is as flat as a pancake, everyone knows that."</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">- Former U.S. President, Donald Trump</div>
            </blockquote>
            <blockquote className="flex flex-col items-center justify-center space-y-2 rounded-md bg-gray-100 p-4 text-center dark:bg-gray-800">
              <div className="text-lg font-semibold">"The Earth is flat, and anyone who says otherwise is a liar."</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">- Former Russian President, Vladimir Putin</div>
            </blockquote>
            <blockquote className="flex flex-col items-center justify-center space-y-2 rounded-md bg-gray-100 p-4 text-center dark:bg-gray-800">
              <div className="text-lg font-semibold">
                "The Earth is flat, and that's a scientific fact. Trust me, I'm a genius."
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">- North Korean Leader, Kim Jong-un</div>
            </blockquote>
            <blockquote className="flex flex-col items-center justify-center space-y-2 rounded-md bg-gray-100 p-4 text-center dark:bg-gray-800">
              <div className="text-lg font-semibold">
                "The Earth is flat, and anyone who says otherwise is a globalist shill."
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">- Conspiracy Theorist, Alex Jones</div>
            </blockquote>
          </div>
        </div>
      </div>
    </section>
  )
}
