/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tCQe0rYw1Og
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import Link from "next/link"
import { Input } from "@nextui-org/input"
import { Card, CardBody, CardHeader, CardFooter, Divider } from "@nextui-org/react"
import { ResponsiveBar } from "@nivo/bar"
import { ResponsiveLine } from "@nivo/line"
import { useState, JSX, SVGProps } from "react"
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, useDisclosure, Button, Checkbox } from "@nextui-org/react"
import { useRouter } from "next/navigation"
import React from "react"

export default function Page() {


    const [isToggled, setIsToggled] = useState(false);
    const handleToggle = () => {
        setIsToggled((prev1) => !prev1);
    };

    const [istrackToggled, setIstrackToggled] = useState(false);
    const handletrackToggle = () => {
        setIstrackToggled((prev) => !prev);
    };

    const { isOpen, onOpen, onClose, onOpenChange } = useDisclosure();

    const [isSelected, setIsSelected] = useState(false);
    const router = useRouter();


    const Modal1 = ({ isOpen, onClose }) => {
        return (
            <Modal size="xl" isOpen={isOpen} onClose={closeModal1} onOpenChange={onOpenChange} >
                <ModalContent>
                    {(onClose) => (
                        <>
                            <ModalHeader>Disconnect Your Google Account?</ModalHeader>
                            <Divider />
                            <ModalBody><p>All linked accounts such as Merchant Center, Ads, YouTube, and/or Analytics will be unlinked and disconnected.</p>
                                <p>If applicable, your products will stop syncing to Google Merchant Center and eventually expire. Any running campaigns will be paused.</p></ModalBody>
                            <Divider />
                            <ModalFooter>
                                <Button onPress={closeModal1} variant="ghost">Cancel</Button>
                                <Button onPress={() => router.push('/connectaccount')} color="danger">Disconnect</Button>
                            </ModalFooter>
                        </>
                    )}
                </ModalContent>
            </Modal>

        );
    };
    const Modal2 = ({ isOpen, onClose }) => {
        return (
            <Modal size="xl" isOpen={isOpen} onClose={closeModal2} onOpenChange={onOpenChange}>
                <ModalContent>
                    {(onClose) => (
                        <>
                            <ModalHeader className="flex flex-col gap-1">Confirm</ModalHeader>
                            <Divider />
                            <ModalBody><p>Is contact Information Visible on your Website?</p>
                            </ModalBody>
                            <Divider />
                            <ModalFooter>
                                <Button onPress={closeModal2} variant="ghost">Cancel</Button>
                                <Button onPress={() => { setIsSelected(true); setIsModal2Open(false) }} color="primary">Confirm</Button>
                            </ModalFooter>
                        </>
                    )}
                </ModalContent>
            </Modal>
        );
    };

    const [isModal1Open, setIsModal1Open] = useState(false);
    const [isModal2Open, setIsModal2Open] = useState(false);

    const openModal1 = () => {
        setIsModal1Open(true);
    };

    const closeModal1 = () => {
        setIsModal1Open(false);
    };
    const openModal2 = () => {
        setIsModal2Open(true);
    };

    const closeModal2 = () => {
        setIsModal2Open(false);
    };
    //};
    return (

        <div className="grid min-h-screen w-full grid-cols-[380px_1fr]">
            <div className=" flex sticky top-0 left-20 flex h-screen flex-col /* border-r */ border-none bg-muted/40 py-20">
                <Card>
                    <CardHeader>
                        <div className="font-semibold">
                            Advertisments Listings
                        </div>
                    </CardHeader>
                    <CardBody>


                        <div className="flex items-center justify-between">
                            <div >
                                Add your Advertisments to Google Center so your listings can appear on Google Shopping, Search, Images,
                                and other places.
                                <Link href="#">Learn more</Link>
                            </div>
                        </div>
                    </CardBody>
                    <Divider />
                    <CardFooter>0/5 Complete store requirements</CardFooter>
                </Card>
            </div>
            <div className="flex flex-col">
                <header className="flex h-14 items-center justify-between px-20" >
                    <h1 className="text-lg font-semibold">Set up the Google & YouTube app</h1>
                </header>
                <main className="flex-1 overflow-auto p-6">
                    <div className="space-y-6">
                        <div className="grid grid-cols-1 max-w-3xl mx-auto space-y-6">
                            <Card>
                                <CardHeader>
                                    <div className="font-semibold">
                                        Looking only to set up Google Analytics 4?
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            You can set up Google Analytics and get insights into your online store performance without a Google Merchant Center account

                                        </div>

                                    </div>
                                </CardBody>
                                <CardFooter>  <Button size="sm" variant="ghost">Get started</Button>
                                    <Link className="underline" href="https://support.google.com/analytics/answer/10089681">Learn more about Google Analytics</Link></CardFooter>
                            </Card>


                            <Card>
                                <CardHeader >
                                    <div>
                                        <p className="font-semibold">Your Google Account</p>
                                        {/* Google Integration*/}
                                        <p>Connect your Google account to access analytics and advertising features.</p>
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="text-sm font-medium">Connected as:</p>
                                            <p className="text-lg font-semibold">example@gmail.com</p>
                                        </div>
                                        <Button onClick={openModal1} size="sm" variant="ghost">Disconnect</Button>
                                        <Modal1 isOpen={isModal1Open} onClose={closeModal1}></Modal1>
                                    </div>
                                </CardBody>
                                <Divider />
                                <CardFooter className="Border-t">
                                    This account is used to sync with Google & YouTube.
                                </CardFooter>
                            </Card>

                            <Card>
                                <CardHeader>
                                    <div className="font-semibold">
                                        Emails from Google app
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p>  You are receiving updates from the Google & YouTube app about new features, tips, surveys, best practices and more.</p>
                                        </div>
                                        <Checkbox color="success" isSelected={isToggled} isDisabled ></Checkbox>
                                        <Button onClick={handleToggle} color={isToggled ? 'default' : 'success'} size="sm" variant="solid">
                                            {isToggled ? 'Turn Off' : 'Turn On'}
                                        </Button>
                                    </div>
                                </CardBody>
                                <CardFooter>
                                    <p className="text-sm font-medium">You can turn these notifications off at any time.</p>
                                </CardFooter>
                            </Card>


                            <Card >
                                <CardHeader>
                                    Requirement check list

                                </CardHeader>
                                <CardBody className="mt-4 border-t pt-4">
                                    <div className="space-y-4">
                                        <div className="flex items-center gap-4">
                                            <Checkbox defaultSelected color="success" isDisabled={true} ></Checkbox>
                                            <div>Add a valid payment method
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-4">
                                            <Checkbox color="success" isDisabled={true} ></Checkbox>

                                            <div><Link href="#">Create a online store</Link>
                                                <p>Remove your online store password</p></div>
                                        </div>
                                        <div className="flex items-center gap-4">
                                            <Checkbox color="success" isDisabled={true} ></Checkbox>
                                            <div><Link href="#" className="underline">Add a refund policy</Link>
                                                <p>Add the refund policy and terms of service to your footer navigation menu</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-4">
                                            <Checkbox id="ContactInfo" isSelected={isSelected} color="success" isDisabled={true} ></Checkbox>
                                            <div><a href="#" className="underline" onClick={isSelected ? (e) => e.preventDefault() : openModal2} >
                                                <p>Confirm that you have added contact information to your online store.</p></a>
                                                <Modal2 isOpen={isModal2Open} onClose={closeModal2} />
                                            </div>
                                        </div>
                                    </div>
                                </CardBody>
                            </Card>


                            {/*  <Card>
                                <CardHeader>
                                    Connect a Google Merchant account

                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="text-sm font-medium"></p>

                                        </div>
                                        <Button size="sm" variant="ghost">Connect</Button>
                                    </div>
                                </CardBody>
                            </Card> */}
                            <Card>
                                <CardHeader>
                                    <div className="font-semibold">
                                        Verify it is you
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="text-sm">Google needs a valid business phone number to activate your Merchant Center account</p>
                                            <p className="text-sm">Enter a mobile or Landline to get a 6-digit Code by text message or voice</p>

                                            <Input
                                                id="name"
                                                label="Phone number"
                                                labelPlacement="outside"
                                                placeholder="Enter your phone number"
                                            /* className="rounded-md border border-input bg-transparent px-3 py-2 text-sm"  */
                                            />

                                        </div>
                                        <Button size="sm" variant="ghost">Get Code</Button>
                                    </div>
                                </CardBody>
                            </Card>
                            <Card>
                                <CardHeader>
                                    <div className="font-semibold">
                                        Your product feed settings</div>
                                    {/*  <Button size="sm" variant="ghost">Manage</Button> */}
                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="text-sm">These settings affect how your products will appear to customers</p>

                                        </div>
                                    </div>
                                </CardBody>
                                <Divider />
                                <CardBody>

                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="text-sm font-medium">Target Country and Language</p>
                                        </div>
                                        <Button size="sm" variant="ghost">Select</Button>
                                    </div>
                                    <div className="flex items-center justify-between py-4">
                                        <div>
                                            <p className="text-sm font-medium">Shipping settings</p>
                                        </div>
                                        <Button size="sm" variant="ghost">Select</Button>
                                    </div>

                                </CardBody>
                            </Card>
                            <Card>
                                <CardHeader>
                                    <div className="font-semibold">
                                        Conversition tracking
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="text-sm">This helps optimize the performance of paid ads and free Listings.It can also give you insights into the most impactful ads Listings,and keywords.</p>

                                        </div>
                                        <Checkbox color="success" radius="sm" isSelected={istrackToggled} disabled ></Checkbox>
                                        <Button onClick={handletrackToggle} color={istrackToggled ? 'default' : 'success'} size="sm" variant="solid">
                                            {istrackToggled ? 'Turn Off' : 'Turn On'}
                                        </Button>

                                    </div>
                                </CardBody>
                            </Card>

                            {/*     </div>
                            <div className="grid grid-cols-2 gap-6"> */}
                            <Card>
                                <CardHeader>
                                    <div className="font-semibold">
                                        Terms and Conditions
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="text-sm">In order to complete setup,you must agree to Google terms of service</p>
                                            <Checkbox>I have read and agree to the terms</Checkbox>

                                        </div>

                                    </div>
                                </CardBody>
                            </Card>
                            <Button variant="ghost">Complete setup</Button></div>
                    </div>

                </main>
            </div>
        </div>

    )
}